name: Build and Push to Docker Hub

# 如果您想推送到 Docker Hub，请使用这个工作流
# 需要在 GitHub 仓库设置中添加 Secrets:
# - DOCKERHUB_USERNAME: 您的 Docker Hub 用户名
# - DOCKERHUB_TOKEN: 您的 Docker Hub 访问令牌

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/everytalk-website
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Success message
        run: |
          echo "✅ Docker image built and pushed successfully!"
          echo "Image: ${{ secrets.DOCKERHUB_USERNAME }}/everytalk-website:latest"

